# Generated by Django 4.0.5 on 2022-06-22 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benson1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='license_number',
            field=models.PositiveIntegerField(default=111111, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
